// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5xqqvraJeKVoAiVmNvnMyv31l_KA9IBQ',
    appId: '1:1054203624552:web:57ee91033f147905990fdd',
    messagingSenderId: '1054203624552',
    projectId: 'condotecfirebase',
    authDomain: 'condotecfirebase.firebaseapp.com',
    storageBucket: 'condotecfirebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxk52ny8yKxCK6a5CGlgm_VZGyygk9xuQ',
    appId: '1:1054203624552:android:282f591f001bb2d1990fdd',
    messagingSenderId: '1054203624552',
    projectId: 'condotecfirebase',
    storageBucket: 'condotecfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3EzGPd3lWUWu9QdOBhn3P_hXozZzQxcI',
    appId: '1:1054203624552:ios:2a770e136093dd70990fdd',
    messagingSenderId: '1054203624552',
    projectId: 'condotecfirebase',
    storageBucket: 'condotecfirebase.firebasestorage.app',
    iosBundleId: 'com.example.condotec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3EzGPd3lWUWu9QdOBhn3P_hXozZzQxcI',
    appId: '1:1054203624552:ios:2a770e136093dd70990fdd',
    messagingSenderId: '1054203624552',
    projectId: 'condotecfirebase',
    storageBucket: 'condotecfirebase.firebasestorage.app',
    iosBundleId: 'com.example.condotec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5xqqvraJeKVoAiVmNvnMyv31l_KA9IBQ',
    appId: '1:1054203624552:web:3796027cdb881d3c990fdd',
    messagingSenderId: '1054203624552',
    projectId: 'condotecfirebase',
    authDomain: 'condotecfirebase.firebaseapp.com',
    storageBucket: 'condotecfirebase.firebasestorage.app',
  );
}
